<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: grpc/proto/hello.proto

namespace Hello;

use OpenSwoole\GRPC;

class HelloClient extends \OpenSwoole\GRPC\BaseStub
{


    /**
    * @param HelloRequest $request
    * @return HelloResponse
    *
    * @throws \OpenSwooleGRPC\Exception\InvokeException
    */
    public function SayHello(HelloRequest $request, $metadata = []): HelloResponse {
    	return $this->_simpleRequest('/hello.Hello/SayHello',
        $request,
        ['\Hello\HelloResponse', 'decode'],
        $metadata); 
    }
}
