<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: grpc/proto/hello.proto

namespace Hello;

use OpenSwoole\GRPC;

interface HelloInterface extends GRPC\ServiceInterface
{
    public const NAME = "/hello.Hello";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HelloRequest $request
    * @return HelloResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SayHello(GRPC\ContextInterface $ctx, HelloRequest $request): HelloResponse;
}
