name: "サンプル"

on:
  workflow_dispatch:
    inputs:
      server_env: 
        description: "環境選択"
        type: choice
        required: true
        options: 
          - "develop"
          - "staging"
          - "production"

env:
  SERVER_ENV: ${{ github.event.inputs.server_env }}

jobs:
  build:
    name: "Check Params"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: check variables
      #   run: |
      #     echo "server_env: ${{ github.event.inputs.server_env }}"
      #     echo "SERVER_ENV: ${{ env.SERVER_ENV }}"

      - name: check dev env
        if: env.SERVER_ENV == 'develop'
        run: |
          echo "server_env: ${{ github.event.inputs.server_env }}"
          echo "SERVER_ENV: ${{ env.SERVER_ENV }}"

      - name: check stg env
        if: env.SERVER_ENV == 'staging'
        run: |
          echo "server_env: ${{ github.event.inputs.server_env }}"
          echo "SERVER_ENV: ${{ env.SERVER_ENV }}"

      - name: check pro env
        if: env.SERVER_ENV == 'production'
        run: |
          echo "server_env: ${{ github.event.inputs.server_env }}"
          echo "SERVER_ENV: ${{ env.SERVER_ENV }}"
